name: demo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.7.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.2.3
  http: ^1.2.0
  shared_preferences: ^2.2.2
  marquee: ^2.2.3
  provider: ^6.1.2
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.3.1
  get: ^4.6.6
  confetti: ^0.7.0
  razorpay_flutter: ^1.3.7
  upi_payment_qrcode_generator: ^1.2.1  
  url_launcher:
  upi_pay: ^1.1.0
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  video_player: 
  connectivity_plus: ^6.0.5
  universal_html: ^2.2.4
  js: ^0.6.7



flutter_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
